Project_NhaXinh/Areas/Admin/Controllers/RoomDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ModelNhaXinh.EF;
using NhaXinhBUS.BUS;

namespace Project_NhaXinh.Areas.Admin.Controllers
{
    public class RoomDetailsController : Controller
	{
		RoomBUS roomBUS = new RoomBUS();
		RoomDetailBUS rodtBUS = new RoomDetailBUS();
		List<RoomDetail> roomDetails;
        // GET: Admin/RoomDetails
        public ActionResult Index()
        {
			roomDetails = rodtBUS.getAllRoom();
            return View(roomDetails);
        }

		
		//public JsonResult getallProduct()
		//{
		//	proList = proBUS.getAllProduct();
		//	return Json(proList.Select(s => new { s.ProName, s.ProImage }), JsonRequestBehavior.AllowGet);
		//}


		// GET: Admin/Products/Details/5
		public ActionResult Details(string id)
		{
			return View(rodtBUS.GetRoomDetail(id));
		}

		//GET: Admin/Products/Create
		public ActionResult Create()
		{
			ViewBag.RooID = new SelectList(roomBUS.getAllRoom(), "RooID", "RooName");
			return View();
		}



		//POST: Admin/Products/Create
		//To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[ValidateInput(false)]
		public ActionResult Create(RoomDetail roomDetail)
		{

			ViewBag.RooID = new SelectList(roomBUS.getAllRoom(), "RooID", "RooName");
			if (ModelState.IsValid)
			{
				Guid guid = Guid.NewGuid();
				roomDetail.RoDID = guid.ToString();
				
				if (rodtBUS.addRoom(roomDetail) == true)
				{
					return RedirectToAction("Index");
				}
				else
				{
					ViewBag.error = "Tên sản phẩm đã tồn tại";
					return View(roomDetail);
				}
			}

			return View(roomDetail);
		}

		// GET: Admin/Products/Edit/5
		public ActionResult Edit(string id)
		{
			RoomDetail roomDetail = rodtBUS.GetRoomDetail(id);
			ViewBag.RooID = new SelectList(roomBUS.getAllRoom(), "RooID", "RooName");
			return View(roomDetail);
		}

		// POST: Admin/Products/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[ValidateInput(false)]
		public ActionResult Edit(RoomDetail roomDetail)
		{
			ViewBag.RooID = new SelectList(roomBUS.getAllRoom(), "RooID", "RooName");
			rodtBUS.editRoom(roomDetail);
			return RedirectToAction("Index");
		}


		// POST: Admin/Products/Delete/5
		[HttpGet]
		public ActionResult Delete(string id)
		{
			rodtBUS.removeRoom(id);
			return RedirectToAction("Index");
		}
	}
}

Project_NhaXinh/Areas/Admin/Views/RoomDetails/Create.cshtml
@model ModelNhaXinh.EF.RoomDetail
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div>
    <div class="right_col" role="main">
        @using (Html.BeginForm("Create", "RoomDetails", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal ">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="" style="margin-left:10px">
                        <h4 class="text-dark font-weight-bold">Thêm mới phòng</h4>

                        <div class=" " style="width:75% ;margin:auto;background-color:white;padding:25px;padding-right:30px ">
                            <div class="row mt-3">
                                <label class="col-3 text-dark " for="">Tên phòng (<span class="text-danger font-weight-bold">*</span>)</label>
                                <input type="text" id="RoDName" name="RoDName" class="col-9 pl-1 pt-1">
                            </div>

                            <div class="row mt-3">
                                <div class="d-flex">
                                    <label class="col-3 text-dark" for=""></label>
                                    <img class="col-2 pl-1 pt-1" width="100px" src="/Assets/Admin/images/pngtree-no-avatar-vector-isolated-on-white-background-png-image_4979074.jpg" id="Slide" /><br />
                                    <a id="btnSelectImage" class="col-3 text-dark mt-4" href="#">Chọn ảnh</a>
                                    <input type="text" id="SrcImgRoom" class="d-none" name="Silde" />
                                </div>
                            </div>
                            <div class="row mt-3">
                                <label class="col-3 text-dark" for="">Loại phòng </label>
                                @Html.DropDownList("RooID", null, htmlAttributes: new { @class = "w-50 pl-1 pt-1" })
                            </div>
                            <div class="row mt-3">
                                <label class="col-3 text-dark" for="">Mô tả (<span class="text-danger font-weight-bold">*</span>)</label>
                                <textarea type="text" id="RoDDescription" name="RoDDescription" class="col-9 pl-1 pt-1"></textarea>
                            </div>
                            <div class="row mt-3">
                                <label class="col-3 text-dark" for="">Meta Description (<span class="text-danger font-weight-bold">*</span>)</label>
                                <textarea id="MetaDescription" name="MetaDescription" class="col-9 pl-1 pt-1 "></textarea>

                            </div>
                            <div class="row mt-3">
                                <label class="col-3 text-dark" for="">Chi tiết (<span class="text-danger font-weight-bold">*</span>)</label>
                                <textarea id="Details" name="Details" class="col-9 pl-1 pt-1 "></textarea>

                            </div>

                            <div class="row mt-3">
                                <label class="col-4 text-dark" for="">Trạng thái </label>
                                @Html.CheckBoxFor(model => model.Status, new { @class = "ml-2 ", @checked = "checked" })

                            </div>

                        </div>
                    </div>

                </div>
                <div class="">
                    <div class="col-md-offset-2 mt-3">
                        <input type="submit" value="Create" class="btn btn-primary" />
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
        }

    </div>
</div>
@section scripts {
    <script type="text/javascript">
        $("#btnSelectImage").on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                document.getElementById("Slide").src = url;
                $("#SrcImgRoom").val(url);
            };
            finder.popup();
        })
    </script>
    <script>
        var editor = CKEDITOR.replace('Details', {
            customConfig: '/Assets/Admin/Plugin/ckeditor/config.js'
        })
    </script>
}

Project_NhaXinh/Areas/Admin/Views/RoomDetails/Details.cshtml
@model ModelNhaXinh.EF.RoomDetail
@{
    ViewBag.Title = Model.RoDName;
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div>
    <div class="right_col" role="main">

        <div class="form-horizontal ">

            <div class="row">
                <div class="" style="margin-left:10px">
                    <div class=" " style="width:75% ;margin: auto;background-color:white;padding:25px;padding-right:30px ">
                        <div class="row mt-3">
                            @Html.Raw(Model.Details)
                        </div>
                        <div class="row mt-4">
                            <label class="col-2 text-dark" for="">Trạng thái </label>
                            @Html.CheckBoxFor(model => model.Status, new { @class = " " })
                        </div>
                    </div>

                </div>

            </div>
            <div class="">
                <div class="col-md-offset-2 mt-3">
                    @Html.ActionLink("Edit", "Edit")
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>

    </div>
</div>

Project_NhaXinh/Areas/Admin/Views/RoomDetails/Edit.cshtml
@model ModelNhaXinh.EF.RoomDetail
@{
    ViewBag.Title = Model.RoDName;
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div>
    <div class="right_col" role="main">
        @using (Html.BeginForm("Edit", "RoomDetails", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal ">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="" style="margin-left:10px">
                        <h4 class="text-dark font-weight-bold">Chỉnh sửa thông tin phòng</h4>

                        <div class=" " style="width:75% ;margin:auto;background-color:white;padding:25px;padding-right:30px ">
                            <div class="row mt-3">
                                <label class="col-3 text-dark " for="">Tên phòng (<span class="text-danger font-weight-bold">*</span>)</label>
                                <input type="text" id="RoDName" value="@Model.RoDName" name="RoDName" class="col-9 pl-1 pt-1">
                                <input type="text" id="RoDID" value="@Model.RoDID" name="RoDID" class="d-none">
                            </div>

                            <div class="row mt-3">
                                <div class="d-flex">
                                    <label class="col-3 text-dark" for=""></label>
                                    <img class="col-2 pl-1 pt-1" width="100px" src="@Model.Silde" id="Silde" /><br />
                                    <a id="btnSelectImage" class="col-3 text-dark mt-4" href="#">Chọn ảnh</a>
                                    <input type="text" id="SrcImgRoom" value="@Model.Silde" class="d-none" name="Silde" />
                                </div>
                            </div>
                            <div class="row mt-3">
                                <label class="col-3 text-dark" for="">Loại phòng </label>
                                @Html.DropDownList("RooID", null, htmlAttributes: new { @class = "w-50 pl-1 pt-1", name = "RooID" })
                            </div>
                            <div class="row mt-3">
                                <label class="col-3 text-dark" for="">Mô tả (<span class="text-danger font-weight-bold">*</span>)</label>
                                <textarea type="text" id="RoDDescription" name="RoDDescription" class="col-9 pl-1 pt-1">@Model.RoDDescription</textarea>
                            </div>
                            <div class="row mt-3">
                                <label class="col-3 text-dark" for="">Meta Description (<span class="text-danger font-weight-bold">*</span>)</label>
                                <textarea id="MetaDescription" name="MetaDescription" class="col-9 pl-1 pt-1 ">@Model.MetaDescription</textarea>

                            </div>
                            <div class="row mt-3">
                                <label class="col-3 text-dark" for="">Chi tiết (<span class="text-danger font-weight-bold">*</span>)</label>
                                <textarea id="Details" name="Details" class="col-9 pl-1 pt-1 ">@Html.Raw(Model.Details)</textarea>

                            </div>

                            <div class="row mt-3">
                                <label class="col-4 text-dark" for="">Trạng thái </label>
                                @Html.CheckBoxFor(model => model.Status, new { @class = "ml-2 ", @checked = "checked" })

                            </div>

                        </div>
                    </div>

                </div>
                <div class="">
                    <div class="col-md-offset-2 mt-3">
                        <input type="submit" value="Edit" class="btn btn-primary" />
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
        }

    </div>
</div>
@section scripts {
    <script type="text/javascript">
        $("#btnSelectImage").on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                document.getElementById("Silde").src = url;
                $("#SrcImgRoom").val(url);
            };
            finder.popup();
        })
    </script>
    <script>
        var editor = CKEDITOR.replace('Details', {
            customConfig: '/Assets/Admin/Plugin/ckeditor/config.js'
        })
    </script>
}

Project_NhaXinh/Areas/Admin/Views/RoomDetails/Index.cshtml
@model IEnumerable<ModelNhaXinh.EF.RoomDetail>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
    int i = 1;
}
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Quản lý chi tiết phòng <small></small></h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-sm-12 ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Quản lý phòng</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Settings 1</a>
                                    <a class="dropdown-item" href="#">Settings 2</a>
                                </div>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card-box table-responsive ">
                                    <button class="float-right btn btn-warning mr-2 text-info">
                                        <i class="glyphicon glyphicon-plus "></i>
                                        @Html.ActionLink("Thêm mới ", "Create")
                                    </button>

                                    <table id="datatable-buttons" class="table bulk_action jambo_table table-striped table-bordered table-hover" style="width:100%">
                                        <thead>
                                            <tr class="headings">
                                                <th><input type="checkbox" id="check-all" class="flat"></th>
                                                <th>STT</th>
                                                <th class="column-title">
                                                    @Html.DisplayNameFor(model => model.Room.RooName)
                                                </th>
                                                <th class="column-title">
                                                    @Html.DisplayNameFor(model => model.RoDName)
                                                </th>
                                                <th class="column-title">
                                                    @Html.DisplayNameFor(model => model.Silde)
                                                </th>
                                                <th class="column-title">
                                                    @Html.DisplayNameFor(model => model.Status)
                                                </th>
                                                <th class="column-title no-link last">Tác vụ</th>
                                                <th class="bulk-actions" colspan="7">
                                                    <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                            <tr id="row_@item.RoDID">
                                                <td class="a-center ">
                                                    <input type="checkbox" class="flat" name="table_records">
                                                </td>
                                                <td>@(i++)</td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Room.RooName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.RoDName)
                                                </td>
                                                <td>
                                                   <img width="50px" src="@item.Silde"/>
                                                </td>
                                                <td>
                                                    @Html.CheckBoxFor(modelItem => item.Status)
                                                </td>
                                                <td class="text-center text-danger" style="font-size: 16px">
                                                    @Html.ActionLink(" ", "Edit", new { id = item.RoDID }, new { @class = "text-danger glyphicon glyphicon-edit" }) |
                                                    @Html.ActionLink(" ", "Details", new { id = item.RoDID }, new { @class = "text-danger glyphicon glyphicon-info-sign" }) |
                                                    @Ajax.ActionLink(" ", "Delete", new { @id = item.RoDID }, new AjaxOptions
                                                   {
                                                       Confirm = "Bạn có chắc chắn muốn xóa ?",
                                                       OnComplete = " $('#row_" + @item.RoDID + "').remove()",
                                                       HttpMethod = "GET"
                                                   }, new { @class = "text-danger glyphicon glyphicon-remove" })

                                                </td>

                                            </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->