Project_NhaXinh/Areas/Admin/Controllers/StuffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ModelNhaXinh.EF;
using NhaXinhBUS.BUS;

namespace Project_NhaXinh.Areas.Admin.Controllers
{
    public class StuffsController : BaseController
    {
        StuffBUS stuBUS = new StuffBUS();
        List<Stuff> stuList;
        // GET: Admin/Stuffs
        public ActionResult Index()
        {
            stuList = stuBUS.getAllStuff();
            return View(stuList);
        }

        // GET: Admin/Stuffs/Create
        public ActionResult Create()
        {
            int a1 = stuBUS.getAllStuff().Count();
            stuList = stuBUS.getAllStuff();
            if (a1 == 0)
            {
                ViewBag.StuID = "ST01";
            }
            else if (a1 < 9)
            {
                a1 = int.Parse(stuList[a1 - 1].StuID.Substring(2)) + 1;
                ViewBag.StuID = "ST0" + a1;
            }
            else
            {
                a1 = int.Parse(stuList[a1 - 1].StuID.Substring(2)) + 1;
                ViewBag.StuID = "ST" + a1;
            }
            ViewBag.CatID = new SelectList(stuBUS.getCat(), "CatID", "CatName");
            return View();
        }

        // POST: Admin/Stuffs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StuID,StuName,StuDescription,CatID")] Stuff stuff)
        {
            if (ModelState.IsValid)
            {
                int a1 = stuBUS.getAllStuff().Count();
                stuList = stuBUS.getAllStuff();
                if (a1 == 0)
                {
                    stuff.StuID = "ST01";
                }
                else if (a1 < 9)
                {
                    a1 = int.Parse(stuList[a1 - 1].StuID.Substring(2)) + 1;
                    stuff.StuID = "ST0" + a1;
                }
                else
                {
                    a1 = int.Parse(stuList[a1 - 1].StuID.Substring(2)) + 1;
                    stuff.StuID = "ST" + a1;
                }
                if (stuBUS.addStuff(stuff) == true)
				{
                    return RedirectToAction("Index");
                }      
                else
				{
                    ViewBag.Erorr = "Mã chất liệu này đã tồn tại";
                    return View();
				}                    
               
            }
            ViewBag.CatID = new SelectList(stuBUS.getCat(), "CatID", "CatName");
            return View(stuff);
        }

       [HttpGet]
        public ActionResult Delete(string id)
        {
            stuBUS.removeStuff(id);
            return RedirectToAction("Index");
        }

    }
}

Project_NhaXinh/Areas/Admin/Views/Stuffs/Create.cshtml
@model ModelNhaXinh.EF.Stuff

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Loại nội thất</h3>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Chỉnh sửa loại nội thất </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Settings 1</a>
                                    <a class="dropdown-item" href="#">Settings 2</a>
                                </div>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content ">
                        @using (Html.BeginForm("Create", "Stuffs", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal ">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="row">
                                    <div class="col-sm-6 pl-3 pr-3" style="margin-top:15px">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.CatID, "CatID", htmlAttributes: new { @class = "text-dark font-weight-bold" })
                                            @Html.DropDownList("CatID", null, htmlAttributes: new { @class = "form-control bg-light" })
                                            @Html.ValidationMessageFor(model => model.CatID, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-6 pl-3 pr-3" style="margin-top:15px">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.StuID, htmlAttributes: new { @class = "text-dark font-weight-bold" })
                                            <input name="StuID" id="StuID" class="form-control bg-light" type="text" disabled value="@ViewBag.StuID" />
                                            @Html.ValidationMessageFor(model => model.StuID, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-6 pl-3 pr-3" style="margin-top:15px">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.StuName, htmlAttributes: new { @class = "text-dark font-weight-bold" })
                                            @Html.TextBoxFor(model => model.StuName, new { @class = "form-control bg-light", required = true })
                                            @Html.ValidationMessageFor(model => model.StuName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-6 pl-3 pr-3" style="margin-top:15px">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.StuDescription, htmlAttributes: new { @class = "text-dark font-weight-bold" })
                                            @Html.TextAreaFor(model => model.StuDescription, new { @class = "form-control bg-light " })
                                            @Html.ValidationMessageFor(model => model.StuDescription, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="">
                                    <div class="col-md-offset-2 mt-3  pl-3">
                                        <input type="submit" value="Create" class="btn btn-danger" />
                                        @Html.ActionLink("Back to List", "Index")
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Project_NhaXinh/Areas/Admin/Views/Stuffs/Edit.cshtml
@model ModelNhaXinh.EF.Stuff

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Loại nội thất</h3>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Chỉnh sửa loại nội thất </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Settings 1</a>
                                    <a class="dropdown-item" href="#">Settings 2</a>
                                </div>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content ">
                        @using (Html.BeginForm("Edit", "Stuffs", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal ">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="row">
                                    <div class="col-sm-6 pl-3 pr-3" style="margin-top:15px">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.CatID, "CatID", htmlAttributes: new { @class = "text-dark font-weight-bold" })
                                            @Html.DropDownList("CatID", null, new { @class = "form-control bg-light" })
                                            @Html.ValidationMessageFor(model => model.CatID, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-6 pl-3 pr-3" style="margin-top:15px">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.StuID, htmlAttributes: new { @class = "text-dark font-weight-bold" })
                                            @Html.TextBoxFor(model => model.StuID, new { @class = "form-control bg-light", required = true })
                                            @Html.ValidationMessageFor(model => model.StuID, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-6 pl-3 pr-3" style="margin-top:15px">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.StuName, htmlAttributes: new { @class = "text-dark font-weight-bold" })
                                            @Html.TextBoxFor(model => model.StuName, new { @class = "form-control bg-light", required = true })
                                            @Html.ValidationMessageFor(model => model.StuName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-sm-6 pl-3 pr-3" style="margin-top:15px">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.StuDescription, htmlAttributes: new { @class = "text-dark font-weight-bold" })
                                            @Html.TextAreaFor(model => model.StuDescription, new { @class = "form-control bg-light ", required = true })
                                            @Html.ValidationMessageFor(model => model.StuDescription, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="">
                                    <div class="col-md-offset-2 mt-3  pl-3">
                                        <input type="submit" value="Save" class="btn btn-danger" />
                                        @Html.ActionLink("Back to List", "Index")
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Project_NhaXinh/Areas/Admin/Views/Stuffs/Index.cshtml
@model IEnumerable<ModelNhaXinh.EF.Stuff>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
    int i = 1;
}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Stuff Management <small></small></h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <!-- <div class="input-group">
                      <input type="text" class="form-control" placeholder="Search for...">
                      <span class="input-group-btn">
                        <button class="btn btn-secondary" type="button">Go!</button>
                      </span>
                    </div> -->
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-sm-12 ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Stuff</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Settings 1</a>
                                    <a class="dropdown-item" href="#">Settings 2</a>
                                </div>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card-box table-responsive ">
                                    <button class="float-right btn btn-warning mr-2 text-info">
                                        <i class="glyphicon glyphicon-plus "></i>
                                        @Html.ActionLink("Thêm mới ", "Create")
                                    </button>

                                    <table id="datatable-buttons" class="table bulk_action jambo_table table-striped table-bordered table-hover" style="width:100%">
                                        <thead>
                                            <tr class="headings">
                                                <th><input type="checkbox" id="check-all" class="flat"></th>
                                                <th>STT</th>
                                                <th class="column-title">
                                                    @Html.DisplayNameFor(model => model.StuID)
                                                </th>
                                                <th class="column-title">
                                                    @Html.DisplayNameFor(model => model.StuName)
                                                </th>
                                                <th class="column-title no-link last">Tác vụ</th>
                                                <th class="bulk-actions" colspan="7">
                                                    <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr id="row_@item.StuID">
                                                    <td class="a-center ">
                                                        <input type="checkbox" class="flat" name="table_records">
                                                    </td>
                                                    <td>@(i++)</td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.StuID)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.StuName)
                                                    </td>
                                                   
                                                    <td class="text-center text-danger" style="font-size: 18px">
                                                        @Html.ActionLink(" ", "Edit", new { id = item.StuID }, new { @class = "text-danger glyphicon glyphicon-edit" }) |
                                                        @Ajax.ActionLink(" ", "Delete", new { @id = item.StuID }, new AjaxOptions
                                                       {
                                                           Confirm = "Bạn có chắc chắn muốn xóa ?",
                                                           OnComplete = " $('#row_" + @item.StuID + "').remove()",
                                                           HttpMethod = "Get"
                                                       }, new { @class = "text-danger glyphicon glyphicon-remove" })

                                                    </td>

                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>